# Simple workflow for deploying static content to GitHub Pages
name: Deploy static content to Pages

on:
  # Runs on pushes targeting the default branch
  push:
    branches: ["main"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow one concurrent deployment
concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  # Single deploy job since we're just deploying
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Pages
        uses: actions/configure-pages@v1
      - name: Get build container
        id: adocbuild
        uses: tonynv/asciidoctor-action@master
        with:
          program: "asciidoctor --backend=html5 -o index.html java-101.adoc"
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          # Upload entire repository
          path: '.'
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@main
  EPUB:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build EPUB
        uses: vepo/asciidoctor-action@v1.3
        with: 
          files: 'java-101.adoc'
          format: epub
          asciidoctor-args: -a toc
          args: "-a revdate=`date +%Y-%m-%d` --failure-level=ERROR"
      - name: Archive EPUB
        uses: actions/upload-artifact@v2
        with:
          name: book-epub
          path: asciidoc-out/java-101.epub